/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_login_window (void);
GtkWidget* create_panneau_admin_window (void);
GtkWidget* create_Ajout___lection (void);
GtkWidget* create_Gestion_elections (void);
GtkWidget* create_electorPannel (void);
GtkWidget* create_ajout_liste_electoral (void);
GtkWidget* create_Reclamation (void);
GtkWidget* create_Ajout_observateur (void);
GtkWidget* create_ajout_bureau_ (void);
GtkWidget* create_Gestion_Bureau_de_vote (void);
GtkWidget* create_PanneauAgent (void);
GtkWidget* create_Confirmation (void);
GtkWidget* create_Gestion_Utilisateurs (void);
GtkWidget* create_admin_window (void);
GtkWidget* create_ajouter_electeur_window (void);
GtkWidget* create_ajouter_observateurs_window (void);
GtkWidget* create_edit_electeur_window (void);
GtkWidget* create_edit_observateur_window (void);
GtkWidget* create_agent_window (void);
