/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_authentification (void)
{
  GtkWidget *authentification;
  GtkWidget *fixed1;
  GtkWidget *vseparator1;
  GtkWidget *Login;
  GtkWidget *mot_de_passe;
  GtkWidget *labellogin;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *button1;

  authentification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (authentification, 496, 376);
  gtk_window_set_title (GTK_WINDOW (authentification), _("window1"));
  gtk_window_set_position (GTK_WINDOW (authentification), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (authentification), FALSE);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (authentification), fixed1);
  gtk_widget_set_size_request (fixed1, -1, 587);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator1, 504, 0);
  gtk_widget_set_size_request (vseparator1, 5, 1000);

  Login = gtk_entry_new ();
  gtk_widget_show (Login);
  gtk_fixed_put (GTK_FIXED (fixed1), Login, 104, 144);
  gtk_widget_set_size_request (Login, 300, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (Login), 8226);

  mot_de_passe = gtk_entry_new ();
  gtk_widget_show (mot_de_passe);
  gtk_fixed_put (GTK_FIXED (fixed1), mot_de_passe, 104, 224);
  gtk_widget_set_size_request (mot_de_passe, 300, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (mot_de_passe), 8226);

  labellogin = gtk_label_new (_("Login "));
  gtk_widget_show (labellogin);
  gtk_fixed_put (GTK_FIXED (fixed1), labellogin, 104, 112);
  gtk_widget_set_size_request (labellogin, 41, 17);

  label2 = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 104, 192);
  gtk_widget_set_size_request (label2, 104, 16);

  label3 = gtk_label_new (_("<b>S'authentifier </b>"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 0, 32);
  gtk_widget_set_size_request (label3, 496, 40);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);

  button1 = gtk_button_new_with_mnemonic (_("Se connecter"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 184, 296);
  gtk_widget_set_size_request (button1, 128, 40);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (authentification, authentification, "authentification");
  GLADE_HOOKUP_OBJECT (authentification, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (authentification, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (authentification, Login, "Login");
  GLADE_HOOKUP_OBJECT (authentification, mot_de_passe, "mot_de_passe");
  GLADE_HOOKUP_OBJECT (authentification, labellogin, "labellogin");
  GLADE_HOOKUP_OBJECT (authentification, label2, "label2");
  GLADE_HOOKUP_OBJECT (authentification, label3, "label3");
  GLADE_HOOKUP_OBJECT (authentification, button1, "button1");

  return authentification;
}

GtkWidget*
create_interface_admin (void)
{
  GtkWidget *interface_admin;
  GtkWidget *fixed2;
  GtkWidget *label72;
  GtkWidget *label73;
  GtkWidget *label74;
  GtkWidget *button16;
  GtkWidget *button17;
  GtkWidget *image14;
  GtkWidget *image15;
  GtkWidget *button18;
  GtkWidget *image16;
  GtkWidget *image13;
  GtkWidget *image12;
  GtkWidget *button19;

  interface_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (interface_admin, 920, 510);
  gtk_window_set_title (GTK_WINDOW (interface_admin), _("espace admin"));
  gtk_window_set_resizable (GTK_WINDOW (interface_admin), FALSE);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (interface_admin), fixed2);

  label72 = gtk_label_new (_("Bonjour"));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed2), label72, 784, 24);
  gtk_widget_set_size_request (label72, 72, 24);

  label73 = gtk_label_new (_("Mr"));
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed2), label73, 834, 28);
  gtk_widget_set_size_request (label73, 49, 15);

  label74 = gtk_label_new (_("<b>admin</b>"));
  gtk_widget_show (label74);
  gtk_fixed_put (GTK_FIXED (fixed2), label74, 792, 40);
  gtk_widget_set_size_request (label74, 96, 24);
  gtk_label_set_use_markup (GTK_LABEL (label74), TRUE);
  gtk_label_set_justify (GTK_LABEL (label74), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label74), TRUE);

  button16 = gtk_button_new_with_mnemonic (_("Gestion bureau \n        de vote"));
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed2), button16, 352, 288);
  gtk_widget_set_size_request (button16, 208, 96);

  button17 = gtk_button_new_with_mnemonic (_("Gestion des\n utilisateurs"));
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed2), button17, 112, 288);
  gtk_widget_set_size_request (button17, 176, 96);

  image14 = create_pixmap (interface_admin, "icons8-flyer-distributor-male-skin-type-2-48.png");
  gtk_widget_show (image14);
  gtk_fixed_put (GTK_FIXED (fixed2), image14, 176, 256);
  gtk_widget_set_size_request (image14, 56, 53);

  image15 = create_pixmap (interface_admin, "icons8-collaborator-male-skin-type-4-48.png");
  gtk_widget_show (image15);
  gtk_fixed_put (GTK_FIXED (fixed2), image15, 424, 256);
  gtk_widget_set_size_request (image15, 56, 45);

  button18 = gtk_button_new_with_mnemonic (_("Gestion des\n   elections"));
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed2), button18, 624, 288);
  gtk_widget_set_size_request (button18, 208, 96);

  image16 = create_pixmap (interface_admin, "icons8-elections-48.png");
  gtk_widget_show (image16);
  gtk_fixed_put (GTK_FIXED (fixed2), image16, 704, 264);
  gtk_widget_set_size_request (image16, 40, 37);

  image13 = create_pixmap (interface_admin, NULL);
  gtk_widget_show (image13);
  gtk_fixed_put (GTK_FIXED (fixed2), image13, 32, 24);
  gtk_widget_set_size_request (image13, 72, 64);

  image12 = create_pixmap (interface_admin, "admin_pannel(1).png");
  gtk_widget_show (image12);
  gtk_fixed_put (GTK_FIXED (fixed2), image12, 144, 0);
  gtk_widget_set_size_request (image12, 640, 136);

  button19 = gtk_button_new_with_mnemonic (_("Deconnecter"));
  gtk_widget_show (button19);
  gtk_fixed_put (GTK_FIXED (fixed2), button19, 784, 72);
  gtk_widget_set_size_request (button19, 98, 24);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (interface_admin, interface_admin, "interface_admin");
  GLADE_HOOKUP_OBJECT (interface_admin, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (interface_admin, label72, "label72");
  GLADE_HOOKUP_OBJECT (interface_admin, label73, "label73");
  GLADE_HOOKUP_OBJECT (interface_admin, label74, "label74");
  GLADE_HOOKUP_OBJECT (interface_admin, button16, "button16");
  GLADE_HOOKUP_OBJECT (interface_admin, button17, "button17");
  GLADE_HOOKUP_OBJECT (interface_admin, image14, "image14");
  GLADE_HOOKUP_OBJECT (interface_admin, image15, "image15");
  GLADE_HOOKUP_OBJECT (interface_admin, button18, "button18");
  GLADE_HOOKUP_OBJECT (interface_admin, image16, "image16");
  GLADE_HOOKUP_OBJECT (interface_admin, image13, "image13");
  GLADE_HOOKUP_OBJECT (interface_admin, image12, "image12");
  GLADE_HOOKUP_OBJECT (interface_admin, button19, "button19");

  return interface_admin;
}

GtkWidget*
create_Ajout___lection (void)
{
  GtkWidget *Ajout___lection;
  GtkWidget *fixed15;
  GtkWidget *button14;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image10;
  GtkWidget *label68;
  GtkWidget *button15;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image11;
  GtkWidget *label69;
  GtkWidget *table5;
  GtkWidget *label63;
  GtkWidget *label65;
  GtkWidget *label66;
  GtkWidget *entry12;
  GtkWidget *entry13;
  GtkWidget *calendar2;
  GtkWidget *label80;
  GtkWidget *comboboxentry2;
  GtkWidget *label70;

  Ajout___lection = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Ajout___lection, 542, 633);
  gtk_window_set_title (GTK_WINDOW (Ajout___lection), _("Ajout \303\251lection"));
  gtk_window_set_resizable (GTK_WINDOW (Ajout___lection), FALSE);

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (Ajout___lection), fixed15);
  gtk_widget_set_size_request (fixed15, 329, 325);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed15), button14, 352, 584);
  gtk_widget_set_size_request (button14, 127, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button14), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image10 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox4), image10, FALSE, FALSE, 0);

  label68 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox4), label68, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label68, 73, 17);

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed15), button15, 216, 584);
  gtk_widget_set_size_request (button15, 127, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button15), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image11 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox5), image11, FALSE, FALSE, 0);

  label69 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (hbox5), label69, FALSE, FALSE, 0);

  table5 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table5);
  gtk_fixed_put (GTK_FIXED (fixed15), table5, 64, 152);
  gtk_widget_set_size_request (table5, 401, 368);
  gtk_table_set_row_spacings (GTK_TABLE (table5), 18);
  gtk_table_set_col_spacings (GTK_TABLE (table5), 21);

  label63 = gtk_label_new (_("Date"));
  gtk_widget_show (label63);
  gtk_table_attach (GTK_TABLE (table5), label63, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label63), 0, 0.5);

  label65 = gtk_label_new (_("Nombre d'habitants"));
  gtk_widget_show (label65);
  gtk_table_attach (GTK_TABLE (table5), label65, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label65), 0, 0.5);

  label66 = gtk_label_new (_("Nombre de conseillers"));
  gtk_widget_show (label66);
  gtk_table_attach (GTK_TABLE (table5), label66, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label66), 0, 0.5);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_table_attach (GTK_TABLE (table5), entry12, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (entry12, FALSE);
  gtk_editable_set_editable (GTK_EDITABLE (entry12), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_table_attach (GTK_TABLE (table5), entry13, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (entry13, FALSE);
  gtk_editable_set_editable (GTK_EDITABLE (entry13), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);
  gtk_entry_set_activates_default (GTK_ENTRY (entry13), TRUE);

  calendar2 = gtk_calendar_new ();
  gtk_widget_show (calendar2);
  gtk_table_attach (GTK_TABLE (table5), calendar2, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_calendar_display_options (GTK_CALENDAR (calendar2),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  label80 = gtk_label_new (_("Municipalit\303\251"));
  gtk_widget_show (label80);
  gtk_table_attach (GTK_TABLE (table5), label80, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label80), 0, 0.5);

  comboboxentry2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry2);
  gtk_table_attach (GTK_TABLE (table5), comboboxentry2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label70 = gtk_label_new (_("<b>Ajouter une  \303\251l\303\251ction</b>"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed15), label70, 16, 40);
  gtk_widget_set_size_request (label70, 512, 48);
  gtk_label_set_use_markup (GTK_LABEL (label70), TRUE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajout___lection, Ajout___lection, "Ajout___lection");
  GLADE_HOOKUP_OBJECT (Ajout___lection, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (Ajout___lection, button14, "button14");
  GLADE_HOOKUP_OBJECT (Ajout___lection, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Ajout___lection, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Ajout___lection, image10, "image10");
  GLADE_HOOKUP_OBJECT (Ajout___lection, label68, "label68");
  GLADE_HOOKUP_OBJECT (Ajout___lection, button15, "button15");
  GLADE_HOOKUP_OBJECT (Ajout___lection, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Ajout___lection, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Ajout___lection, image11, "image11");
  GLADE_HOOKUP_OBJECT (Ajout___lection, label69, "label69");
  GLADE_HOOKUP_OBJECT (Ajout___lection, table5, "table5");
  GLADE_HOOKUP_OBJECT (Ajout___lection, label63, "label63");
  GLADE_HOOKUP_OBJECT (Ajout___lection, label65, "label65");
  GLADE_HOOKUP_OBJECT (Ajout___lection, label66, "label66");
  GLADE_HOOKUP_OBJECT (Ajout___lection, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (Ajout___lection, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (Ajout___lection, calendar2, "calendar2");
  GLADE_HOOKUP_OBJECT (Ajout___lection, label80, "label80");
  GLADE_HOOKUP_OBJECT (Ajout___lection, comboboxentry2, "comboboxentry2");
  GLADE_HOOKUP_OBJECT (Ajout___lection, label70, "label70");

  return Ajout___lection;
}

GtkWidget*
create_Ajouter_Utilisateur (void)
{
  GtkWidget *Ajouter_Utilisateur;
  GtkWidget *fixed13;
  GtkWidget *table3;
  GtkWidget *Nom;
  GtkWidget *Pr__nom;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *comboboxentry1;
  GtkWidget *calendar1;
  GtkWidget *button11;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image7;
  GtkWidget *label46;
  GtkWidget *button12;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image8;
  GtkWidget *label47;
  GtkWidget *label48;

  Ajouter_Utilisateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Ajouter_Utilisateur, 500, 740);
  gtk_window_set_title (GTK_WINDOW (Ajouter_Utilisateur), _("Ajouter Utilisateur"));
  gtk_window_set_position (GTK_WINDOW (Ajouter_Utilisateur), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (Ajouter_Utilisateur), FALSE);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (Ajouter_Utilisateur), fixed13);
  gtk_widget_set_size_request (fixed13, 0, 0);

  table3 = gtk_table_new (7, 2, FALSE);
  gtk_widget_show (table3);
  gtk_fixed_put (GTK_FIXED (fixed13), table3, 48, 160);
  gtk_widget_set_size_request (table3, 375, 248);
  gtk_table_set_row_spacings (GTK_TABLE (table3), 10);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 20);

  Nom = gtk_label_new (_("Nom"));
  gtk_widget_show (Nom);
  gtk_table_attach (GTK_TABLE (table3), Nom, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (Nom), 0, 0.5);

  Pr__nom = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (Pr__nom);
  gtk_table_attach (GTK_TABLE (table3), Pr__nom, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (Pr__nom), 0, 0.5);

  label41 = gtk_label_new (_("CIN"));
  gtk_widget_show (label41);
  gtk_table_attach (GTK_TABLE (table3), label41, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label41), 0, 0.5);

  label42 = gtk_label_new (_("Date de Naissance"));
  gtk_widget_show (label42);
  gtk_table_attach (GTK_TABLE (table3), label42, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label42), 0, 0.5);

  label43 = gtk_label_new (_("Login"));
  gtk_widget_show (label43);
  gtk_table_attach (GTK_TABLE (table3), label43, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label43), 0, 0.5);

  label44 = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label44);
  gtk_table_attach (GTK_TABLE (table3), label44, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label44), 0, 0.5);

  label45 = gtk_label_new (_("Role"));
  gtk_widget_show (label45);
  gtk_table_attach (GTK_TABLE (table3), label45, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label45), 0, 0.5);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_table_attach (GTK_TABLE (table3), entry3, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_table_attach (GTK_TABLE (table3), entry4, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_table_attach (GTK_TABLE (table3), entry5, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_table_attach (GTK_TABLE (table3), entry7, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_table_attach (GTK_TABLE (table3), entry8, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_table_attach (GTK_TABLE (table3), comboboxentry1, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_table_attach (GTK_TABLE (table3), calendar1, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed13), button11, 320, 632);
  gtk_widget_set_size_request (button11, 120, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button11), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image7 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox1), image7, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox1), label46, FALSE, FALSE, 0);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed13), button12, 184, 632);
  gtk_widget_set_size_request (button12, 120, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button12), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image8 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox2), image8, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox2), label47, FALSE, FALSE, 0);

  label48 = gtk_label_new (_("<b>Ajouter Un Utilisateur</b>"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed13), label48, 0, 24);
  gtk_widget_set_size_request (label48, 496, 64);
  gtk_label_set_use_markup (GTK_LABEL (label48), TRUE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter_Utilisateur, Ajouter_Utilisateur, "Ajouter_Utilisateur");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, table3, "table3");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, Nom, "Nom");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, Pr__nom, "Pr__nom");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, label41, "label41");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, label42, "label42");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, label43, "label43");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, label44, "label44");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, label45, "label45");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, button11, "button11");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, image7, "image7");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, label46, "label46");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, button12, "button12");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, image8, "image8");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, label47, "label47");
  GLADE_HOOKUP_OBJECT (Ajouter_Utilisateur, label48, "label48");

  return Ajouter_Utilisateur;
}

GtkWidget*
create_Gestion_elections (void)
{
  GtkWidget *Gestion_elections;
  GtkWidget *fixed16;
  GtkWidget *treeview6;
  GtkWidget *button20;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image18;
  GtkWidget *label75;
  GtkWidget *image17;
  GtkWidget *label78;
  GtkWidget *label79;
  GtkWidget *image21;
  GtkWidget *button23;
  GtkWidget *button22;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image20;
  GtkWidget *label77;
  GtkWidget *button21;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image19;
  GtkWidget *label76;

  Gestion_elections = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Gestion_elections, 920, 510);
  gtk_window_set_title (GTK_WINDOW (Gestion_elections), _("Gestion d'elections"));
  gtk_window_set_position (GTK_WINDOW (Gestion_elections), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (Gestion_elections), FALSE);

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (Gestion_elections), fixed16);

  treeview6 = gtk_tree_view_new ();
  gtk_widget_show (treeview6);
  gtk_fixed_put (GTK_FIXED (fixed16), treeview6, 72, 160);
  gtk_widget_set_size_request (treeview6, 768, 248);

  button20 = gtk_button_new ();
  gtk_widget_show (button20);
  gtk_fixed_put (GTK_FIXED (fixed16), button20, 752, 432);
  gtk_widget_set_size_request (button20, 88, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button20), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image18 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox6), image18, FALSE, FALSE, 0);

  label75 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label75);
  gtk_box_pack_start (GTK_BOX (hbox6), label75, FALSE, FALSE, 0);

  image17 = create_pixmap (Gestion_elections, "gestion_election_title.png");
  gtk_widget_show (image17);
  gtk_fixed_put (GTK_FIXED (fixed16), image17, 256, 24);
  gtk_widget_set_size_request (image17, 400, 64);

  label78 = gtk_label_new (_("Boujour Mr"));
  gtk_widget_show (label78);
  gtk_fixed_put (GTK_FIXED (fixed16), label78, 768, 24);
  gtk_widget_set_size_request (label78, 112, 32);

  label79 = gtk_label_new (_("<b>Admin</b>"));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed16), label79, 784, 48);
  gtk_widget_set_size_request (label79, 80, 24);
  gtk_label_set_use_markup (GTK_LABEL (label79), TRUE);

  image21 = create_pixmap (Gestion_elections, NULL);
  gtk_widget_show (image21);
  gtk_fixed_put (GTK_FIXED (fixed16), image21, 40, 24);
  gtk_widget_set_size_request (image21, 80, 56);

  button23 = gtk_button_new_with_mnemonic (_("Deconnecter"));
  gtk_widget_show (button23);
  gtk_fixed_put (GTK_FIXED (fixed16), button23, 768, 72);
  gtk_widget_set_size_request (button23, 104, 24);

  button22 = gtk_button_new ();
  gtk_widget_show (button22);
  gtk_fixed_put (GTK_FIXED (fixed16), button22, 496, 432);
  gtk_widget_set_size_request (button22, 112, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button22), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image20 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox8), image20, FALSE, FALSE, 0);

  label77 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label77);
  gtk_box_pack_start (GTK_BOX (hbox8), label77, FALSE, FALSE, 0);

  button21 = gtk_button_new ();
  gtk_widget_show (button21);
  gtk_fixed_put (GTK_FIXED (fixed16), button21, 624, 432);
  gtk_widget_set_size_request (button21, 104, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button21), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image19 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox7), image19, FALSE, FALSE, 0);

  label76 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label76);
  gtk_box_pack_start (GTK_BOX (hbox7), label76, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_elections, Gestion_elections, "Gestion_elections");
  GLADE_HOOKUP_OBJECT (Gestion_elections, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (Gestion_elections, treeview6, "treeview6");
  GLADE_HOOKUP_OBJECT (Gestion_elections, button20, "button20");
  GLADE_HOOKUP_OBJECT (Gestion_elections, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Gestion_elections, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Gestion_elections, image18, "image18");
  GLADE_HOOKUP_OBJECT (Gestion_elections, label75, "label75");
  GLADE_HOOKUP_OBJECT (Gestion_elections, image17, "image17");
  GLADE_HOOKUP_OBJECT (Gestion_elections, label78, "label78");
  GLADE_HOOKUP_OBJECT (Gestion_elections, label79, "label79");
  GLADE_HOOKUP_OBJECT (Gestion_elections, image21, "image21");
  GLADE_HOOKUP_OBJECT (Gestion_elections, button23, "button23");
  GLADE_HOOKUP_OBJECT (Gestion_elections, button22, "button22");
  GLADE_HOOKUP_OBJECT (Gestion_elections, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Gestion_elections, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Gestion_elections, image20, "image20");
  GLADE_HOOKUP_OBJECT (Gestion_elections, label77, "label77");
  GLADE_HOOKUP_OBJECT (Gestion_elections, button21, "button21");
  GLADE_HOOKUP_OBJECT (Gestion_elections, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Gestion_elections, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Gestion_elections, image19, "image19");
  GLADE_HOOKUP_OBJECT (Gestion_elections, label76, "label76");

  return Gestion_elections;
}

GtkWidget*
create_electorPannel (void)
{
  GtkWidget *electorPannel;
  GtkWidget *fixed17;
  GtkWidget *label81;
  GtkWidget *label82;
  GtkWidget *button26;
  GtkWidget *image25;
  GtkWidget *image24;
  GtkWidget *button24;
  GtkWidget *image23;
  GtkWidget *button43;
  GtkWidget *image44;
  GtkWidget *button25;
  GtkWidget *image22;
  GtkWidget *button44;
  GtkWidget *image45;

  electorPannel = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (electorPannel), _("panneau d'electeur"));

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (electorPannel), fixed17);
  gtk_widget_set_size_request (fixed17, 920, 510);

  label81 = gtk_label_new (_("Bonjour Mr"));
  gtk_widget_show (label81);
  gtk_fixed_put (GTK_FIXED (fixed17), label81, 804, 24);
  gtk_widget_set_size_request (label81, 88, 24);

  label82 = gtk_label_new (_("<b>Electeur</b>"));
  gtk_widget_show (label82);
  gtk_fixed_put (GTK_FIXED (fixed17), label82, 808, 48);
  gtk_widget_set_size_request (label82, 88, 24);
  gtk_label_set_use_markup (GTK_LABEL (label82), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (label82), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label82), 0.49, 0.5);

  button26 = gtk_button_new_with_mnemonic (_("Deconnecter"));
  gtk_widget_show (button26);
  gtk_fixed_put (GTK_FIXED (fixed17), button26, 808, 72);
  gtk_widget_set_size_request (button26, 98, 24);

  image25 = create_pixmap (electorPannel, "electorPannel.png");
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed17), image25, 184, 24);
  gtk_widget_set_size_request (image25, 536, 88);

  image24 = create_pixmap (electorPannel, NULL);
  gtk_widget_show (image24);
  gtk_fixed_put (GTK_FIXED (fixed17), image24, 32, 24);
  gtk_widget_set_size_request (image24, 56, 56);

  button24 = gtk_button_new_with_mnemonic (_("Ajout d'une liste\n        electorale"));
  gtk_widget_show (button24);
  gtk_fixed_put (GTK_FIXED (fixed17), button24, 520, 184);
  gtk_widget_set_size_request (button24, 176, 104);

  image23 = create_pixmap (electorPannel, "icons8-add-list-48.png");
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (fixed17), image23, 576, 160);
  gtk_widget_set_size_request (image23, 64, 45);

  button43 = gtk_button_new_with_mnemonic (_("Modifier une liste\n          electorale"));
  gtk_widget_show (button43);
  gtk_fixed_put (GTK_FIXED (fixed17), button43, 248, 336);
  gtk_widget_set_size_request (button43, 168, 104);

  image44 = create_pixmap (electorPannel, "icons8-edit-property-48.png");
  gtk_widget_show (image44);
  gtk_fixed_put (GTK_FIXED (fixed17), image44, 312, 312);
  gtk_widget_set_size_request (image44, 48, 45);

  button25 = gtk_button_new_with_mnemonic (_("Voter"));
  gtk_widget_show (button25);
  gtk_fixed_put (GTK_FIXED (fixed17), button25, 240, 184);
  gtk_widget_set_size_request (button25, 184, 104);

  image22 = create_pixmap (electorPannel, "icons8-elections-48.png");
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed17), image22, 304, 152);
  gtk_widget_set_size_request (image22, 64, 72);

  button44 = gtk_button_new_with_mnemonic (_("Supprimer une liste\n           electorale"));
  gtk_widget_show (button44);
  gtk_fixed_put (GTK_FIXED (fixed17), button44, 520, 344);
  gtk_widget_set_size_request (button44, 168, 104);

  image45 = create_pixmap (electorPannel, "icons8-delete-document-48.png");
  gtk_widget_show (image45);
  gtk_fixed_put (GTK_FIXED (fixed17), image45, 584, 312);
  gtk_widget_set_size_request (image45, 48, 56);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (electorPannel, electorPannel, "electorPannel");
  GLADE_HOOKUP_OBJECT (electorPannel, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (electorPannel, label81, "label81");
  GLADE_HOOKUP_OBJECT (electorPannel, label82, "label82");
  GLADE_HOOKUP_OBJECT (electorPannel, button26, "button26");
  GLADE_HOOKUP_OBJECT (electorPannel, image25, "image25");
  GLADE_HOOKUP_OBJECT (electorPannel, image24, "image24");
  GLADE_HOOKUP_OBJECT (electorPannel, button24, "button24");
  GLADE_HOOKUP_OBJECT (electorPannel, image23, "image23");
  GLADE_HOOKUP_OBJECT (electorPannel, button43, "button43");
  GLADE_HOOKUP_OBJECT (electorPannel, image44, "image44");
  GLADE_HOOKUP_OBJECT (electorPannel, button25, "button25");
  GLADE_HOOKUP_OBJECT (electorPannel, image22, "image22");
  GLADE_HOOKUP_OBJECT (electorPannel, button44, "button44");
  GLADE_HOOKUP_OBJECT (electorPannel, image45, "image45");

  return electorPannel;
}

GtkWidget*
create_ajout_liste_electoral (void)
{
  GtkWidget *ajout_liste_electoral;
  GtkWidget *fixed18;
  GtkWidget *label83;
  GtkWidget *table6;
  GtkWidget *label84;
  GtkWidget *entry14;
  GtkWidget *label85;
  GtkWidget *label86;
  GtkWidget *label87;
  GtkWidget *label88;
  GtkWidget *entry15;
  GtkWidget *entry16;
  GtkWidget *entry17;
  GtkWidget *comboboxentry3;
  GtkWidget *button27;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image26;
  GtkWidget *label89;
  GtkWidget *button28;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image27;
  GtkWidget *label90;

  ajout_liste_electoral = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ajout_liste_electoral, 500, 452);
  gtk_window_set_title (GTK_WINDOW (ajout_liste_electoral), _("ajout de liste electorale"));
  gtk_window_set_position (GTK_WINDOW (ajout_liste_electoral), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (ajout_liste_electoral), FALSE);

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_container_add (GTK_CONTAINER (ajout_liste_electoral), fixed18);

  label83 = gtk_label_new (_("<b>Ajouter une liste electorale</b>"));
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed18), label83, 8, 16);
  gtk_widget_set_size_request (label83, 480, 48);
  gtk_label_set_use_markup (GTK_LABEL (label83), TRUE);

  table6 = gtk_table_new (5, 2, FALSE);
  gtk_widget_show (table6);
  gtk_fixed_put (GTK_FIXED (fixed18), table6, 64, 128);
  gtk_widget_set_size_request (table6, 384, 224);
  gtk_table_set_row_spacings (GTK_TABLE (table6), 19);
  gtk_table_set_col_spacings (GTK_TABLE (table6), 25);

  label84 = gtk_label_new (_("ID tete de la liste"));
  gtk_widget_show (label84);
  gtk_table_attach (GTK_TABLE (table6), label84, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label84), 0, 0.5);

  entry14 = gtk_entry_new ();
  gtk_widget_show (entry14);
  gtk_table_attach (GTK_TABLE (table6), entry14, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (entry14, FALSE);
  gtk_editable_set_editable (GTK_EDITABLE (entry14), FALSE);
  gtk_entry_set_text (GTK_ENTRY (entry14), _("default_id"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 8226);

  label85 = gtk_label_new (_("Orientation"));
  gtk_widget_show (label85);
  gtk_table_attach (GTK_TABLE (table6), label85, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label85), 0, 0.5);

  label86 = gtk_label_new (_("ID condidat 1"));
  gtk_widget_show (label86);
  gtk_table_attach (GTK_TABLE (table6), label86, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label86), 0, 0.5);

  label87 = gtk_label_new (_("ID condidat 2"));
  gtk_widget_show (label87);
  gtk_table_attach (GTK_TABLE (table6), label87, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label87), 0, 0.5);

  label88 = gtk_label_new (_("ID condidat 3"));
  gtk_widget_show (label88);
  gtk_table_attach (GTK_TABLE (table6), label88, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label88), 0, 0.5);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_table_attach (GTK_TABLE (table6), entry15, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);

  entry16 = gtk_entry_new ();
  gtk_widget_show (entry16);
  gtk_table_attach (GTK_TABLE (table6), entry16, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16), 8226);

  entry17 = gtk_entry_new ();
  gtk_widget_show (entry17);
  gtk_table_attach (GTK_TABLE (table6), entry17, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry17), 8226);

  comboboxentry3 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry3);
  gtk_table_attach (GTK_TABLE (table6), comboboxentry3, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  button27 = gtk_button_new ();
  gtk_widget_show (button27);
  gtk_fixed_put (GTK_FIXED (fixed18), button27, 352, 392);
  gtk_widget_set_size_request (button27, 96, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button27), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image26 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox9), image26, FALSE, FALSE, 0);

  label89 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label89);
  gtk_box_pack_start (GTK_BOX (hbox9), label89, FALSE, FALSE, 0);

  button28 = gtk_button_new ();
  gtk_widget_show (button28);
  gtk_fixed_put (GTK_FIXED (fixed18), button28, 232, 392);
  gtk_widget_set_size_request (button28, 104, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button28), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image27 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox10), image27, FALSE, FALSE, 0);

  label90 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label90);
  gtk_box_pack_start (GTK_BOX (hbox10), label90, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_liste_electoral, ajout_liste_electoral, "ajout_liste_electoral");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, label83, "label83");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, table6, "table6");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, label84, "label84");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, entry14, "entry14");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, label85, "label85");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, label86, "label86");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, label87, "label87");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, label88, "label88");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, entry16, "entry16");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, entry17, "entry17");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, comboboxentry3, "comboboxentry3");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, button27, "button27");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, image26, "image26");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, label89, "label89");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, button28, "button28");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, image27, "image27");
  GLADE_HOOKUP_OBJECT (ajout_liste_electoral, label90, "label90");

  return ajout_liste_electoral;
}

GtkWidget*
create_Reclamation (void)
{
  GtkWidget *Reclamation;
  GtkWidget *fixed19;
  GtkWidget *table7;
  GtkWidget *label91;
  GtkWidget *comboboxentry4;
  GtkWidget *label92;
  GtkWidget *comboboxentry5;
  GtkWidget *label93;
  GtkWidget *entry18;
  GtkWidget *label94;
  GtkWidget *scrolledwindow1;
  GtkWidget *textview1;
  GtkWidget *label95;
  GtkWidget *button29;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image29;
  GtkWidget *label97;
  GtkWidget *button30;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image28;
  GtkWidget *label96;

  Reclamation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Reclamation, 600, 500);
  gtk_window_set_title (GTK_WINDOW (Reclamation), _("Reclamation"));
  gtk_window_set_position (GTK_WINDOW (Reclamation), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (Reclamation), FALSE);

  fixed19 = gtk_fixed_new ();
  gtk_widget_show (fixed19);
  gtk_container_add (GTK_CONTAINER (Reclamation), fixed19);

  table7 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table7);
  gtk_fixed_put (GTK_FIXED (fixed19), table7, 40, 112);
  gtk_widget_set_size_request (table7, 512, 296);
  gtk_table_set_row_spacings (GTK_TABLE (table7), 15);
  gtk_table_set_col_spacings (GTK_TABLE (table7), 30);

  label91 = gtk_label_new (_("Type de reclamation"));
  gtk_widget_show (label91);
  gtk_table_attach (GTK_TABLE (table7), label91, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label91), 0, 0.5);

  comboboxentry4 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry4);
  gtk_table_attach (GTK_TABLE (table7), comboboxentry4, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label92 = gtk_label_new (_("Liste reclamee"));
  gtk_widget_show (label92);
  gtk_table_attach (GTK_TABLE (table7), label92, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label92), 0, 0.5);

  comboboxentry5 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry5);
  gtk_table_attach (GTK_TABLE (table7), comboboxentry5, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label93 = gtk_label_new (_("Numero de bureau"));
  gtk_widget_show (label93);
  gtk_table_attach (GTK_TABLE (table7), label93, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label93), 0, 0.5);

  entry18 = gtk_entry_new ();
  gtk_widget_show (entry18);
  gtk_table_attach (GTK_TABLE (table7), entry18, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (entry18), _("precalcul\303\251"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry18), 8226);

  label94 = gtk_label_new (_("Texte de reclamation"));
  gtk_widget_show (label94);
  gtk_table_attach (GTK_TABLE (table7), label94, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label94), 0, 0.5);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_table_attach (GTK_TABLE (table7), scrolledwindow1, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_size_request (scrolledwindow1, -1, 139);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), textview1);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (textview1), GTK_WRAP_WORD);
  gtk_text_view_set_pixels_above_lines (GTK_TEXT_VIEW (textview1), 11);
  gtk_text_view_set_pixels_inside_wrap (GTK_TEXT_VIEW (textview1), 10);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview1)), _("here is some text to tryout how this text entry works and how it wraps text and so far the results are pretty good"), -1);

  label95 = gtk_label_new (_("<b>Envoyer une reclamation</b>"));
  gtk_widget_show (label95);
  gtk_fixed_put (GTK_FIXED (fixed19), label95, 8, 24);
  gtk_widget_set_size_request (label95, 576, 48);
  gtk_label_set_use_markup (GTK_LABEL (label95), TRUE);

  button29 = gtk_button_new ();
  gtk_widget_show (button29);
  gtk_fixed_put (GTK_FIXED (fixed19), button29, 464, 432);
  gtk_widget_set_size_request (button29, 88, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button29), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image29 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox12), image29, FALSE, FALSE, 0);

  label97 = gtk_label_new_with_mnemonic (_("Envoyer"));
  gtk_widget_show (label97);
  gtk_box_pack_start (GTK_BOX (hbox12), label97, FALSE, FALSE, 0);

  button30 = gtk_button_new ();
  gtk_widget_show (button30);
  gtk_fixed_put (GTK_FIXED (fixed19), button30, 352, 432);
  gtk_widget_set_size_request (button30, 88, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button30), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image28 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox11), image28, FALSE, FALSE, 0);

  label96 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label96);
  gtk_box_pack_start (GTK_BOX (hbox11), label96, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Reclamation, Reclamation, "Reclamation");
  GLADE_HOOKUP_OBJECT (Reclamation, fixed19, "fixed19");
  GLADE_HOOKUP_OBJECT (Reclamation, table7, "table7");
  GLADE_HOOKUP_OBJECT (Reclamation, label91, "label91");
  GLADE_HOOKUP_OBJECT (Reclamation, comboboxentry4, "comboboxentry4");
  GLADE_HOOKUP_OBJECT (Reclamation, label92, "label92");
  GLADE_HOOKUP_OBJECT (Reclamation, comboboxentry5, "comboboxentry5");
  GLADE_HOOKUP_OBJECT (Reclamation, label93, "label93");
  GLADE_HOOKUP_OBJECT (Reclamation, entry18, "entry18");
  GLADE_HOOKUP_OBJECT (Reclamation, label94, "label94");
  GLADE_HOOKUP_OBJECT (Reclamation, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (Reclamation, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (Reclamation, label95, "label95");
  GLADE_HOOKUP_OBJECT (Reclamation, button29, "button29");
  GLADE_HOOKUP_OBJECT (Reclamation, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Reclamation, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Reclamation, image29, "image29");
  GLADE_HOOKUP_OBJECT (Reclamation, label97, "label97");
  GLADE_HOOKUP_OBJECT (Reclamation, button30, "button30");
  GLADE_HOOKUP_OBJECT (Reclamation, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Reclamation, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Reclamation, image28, "image28");
  GLADE_HOOKUP_OBJECT (Reclamation, label96, "label96");

  return Reclamation;
}

GtkWidget*
create_Ajout_observateur (void)
{
  GtkWidget *Ajout_observateur;
  GtkWidget *fixed20;
  GtkWidget *label98;
  GtkWidget *table8;
  GtkWidget *label99;
  GtkWidget *label100;
  GtkWidget *label101;
  GtkWidget *label102;
  GtkWidget *label103;
  GtkWidget *label104;
  GtkWidget *comboboxentry6;
  GtkWidget *comboboxentry7;
  GtkWidget *entry19;
  GtkWidget *entry20;
  GtkWidget *entry21;
  GtkWidget *entry22;
  GtkWidget *button31;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image30;
  GtkWidget *label105;
  GtkWidget *button32;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image31;
  GtkWidget *label106;

  Ajout_observateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Ajout_observateur, 500, 573);
  gtk_window_set_title (GTK_WINDOW (Ajout_observateur), _("Ajouter un observateur"));
  gtk_window_set_resizable (GTK_WINDOW (Ajout_observateur), FALSE);

  fixed20 = gtk_fixed_new ();
  gtk_widget_show (fixed20);
  gtk_container_add (GTK_CONTAINER (Ajout_observateur), fixed20);

  label98 = gtk_label_new (_("<b>Ajouter un observateur</b>"));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed20), label98, 0, 40);
  gtk_widget_set_size_request (label98, 496, 56);
  gtk_label_set_use_markup (GTK_LABEL (label98), TRUE);

  table8 = gtk_table_new (6, 2, FALSE);
  gtk_widget_show (table8);
  gtk_fixed_put (GTK_FIXED (fixed20), table8, 32, 168);
  gtk_widget_set_size_request (table8, 440, 272);
  gtk_table_set_row_spacings (GTK_TABLE (table8), 15);
  gtk_table_set_col_spacings (GTK_TABLE (table8), 35);

  label99 = gtk_label_new (_("CIN"));
  gtk_widget_show (label99);
  gtk_table_attach (GTK_TABLE (table8), label99, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label99), 0, 0.5);

  label100 = gtk_label_new (_("Nom"));
  gtk_widget_show (label100);
  gtk_table_attach (GTK_TABLE (table8), label100, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label100), 0, 0.5);

  label101 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label101);
  gtk_table_attach (GTK_TABLE (table8), label101, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label101), 0, 0.5);

  label102 = gtk_label_new (_("Nationalit\303\251"));
  gtk_widget_show (label102);
  gtk_table_attach (GTK_TABLE (table8), label102, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label102), 0, 0.5);

  label103 = gtk_label_new (_("sexe"));
  gtk_widget_show (label103);
  gtk_table_attach (GTK_TABLE (table8), label103, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label103), 0, 0.5);

  label104 = gtk_label_new (_("Appartenance"));
  gtk_widget_show (label104);
  gtk_table_attach (GTK_TABLE (table8), label104, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label104), 0, 0.5);

  comboboxentry6 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry6);
  gtk_table_attach (GTK_TABLE (table8), comboboxentry6, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  comboboxentry7 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry7);
  gtk_table_attach (GTK_TABLE (table8), comboboxentry7, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  entry19 = gtk_entry_new ();
  gtk_widget_show (entry19);
  gtk_table_attach (GTK_TABLE (table8), entry19, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry19), 8226);

  entry20 = gtk_entry_new ();
  gtk_widget_show (entry20);
  gtk_table_attach (GTK_TABLE (table8), entry20, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry20), 8226);

  entry21 = gtk_entry_new ();
  gtk_widget_show (entry21);
  gtk_table_attach (GTK_TABLE (table8), entry21, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry21), 8226);

  entry22 = gtk_entry_new ();
  gtk_widget_show (entry22);
  gtk_table_attach (GTK_TABLE (table8), entry22, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry22), 8226);

  button31 = gtk_button_new ();
  gtk_widget_show (button31);
  gtk_fixed_put (GTK_FIXED (fixed20), button31, 384, 472);
  gtk_widget_set_size_request (button31, 88, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button31), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image30 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox13), image30, FALSE, FALSE, 0);

  label105 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label105);
  gtk_box_pack_start (GTK_BOX (hbox13), label105, FALSE, FALSE, 0);

  button32 = gtk_button_new ();
  gtk_widget_show (button32);
  gtk_fixed_put (GTK_FIXED (fixed20), button32, 280, 472);
  gtk_widget_set_size_request (button32, 88, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button32), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image31 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox14), image31, FALSE, FALSE, 0);

  label106 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label106);
  gtk_box_pack_start (GTK_BOX (hbox14), label106, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajout_observateur, Ajout_observateur, "Ajout_observateur");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, fixed20, "fixed20");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, label98, "label98");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, table8, "table8");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, label99, "label99");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, label100, "label100");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, label101, "label101");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, label102, "label102");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, label103, "label103");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, label104, "label104");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, comboboxentry6, "comboboxentry6");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, comboboxentry7, "comboboxentry7");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, entry19, "entry19");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, entry20, "entry20");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, entry21, "entry21");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, entry22, "entry22");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, button31, "button31");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, image30, "image30");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, label105, "label105");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, button32, "button32");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, image31, "image31");
  GLADE_HOOKUP_OBJECT (Ajout_observateur, label106, "label106");

  return Ajout_observateur;
}

GtkWidget*
create_ajout_bureau_ (void)
{
  GtkWidget *ajout_bureau_;
  GtkWidget *fixed21;
  GtkWidget *label107;
  GtkWidget *table9;
  GtkWidget *label108;
  GtkWidget *label109;
  GtkWidget *label110;
  GtkWidget *label111;
  GtkWidget *scrolledwindow2;
  GtkWidget *textview2;
  GtkWidget *entry23;
  GtkWidget *entry24;
  GtkWidget *entry25;
  GtkWidget *button33;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image32;
  GtkWidget *label112;
  GtkWidget *button34;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image33;
  GtkWidget *label113;

  ajout_bureau_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ajout_bureau_, 500, 600);
  gtk_window_set_title (GTK_WINDOW (ajout_bureau_), _("Ajouter bureau de vote"));
  gtk_window_set_resizable (GTK_WINDOW (ajout_bureau_), FALSE);

  fixed21 = gtk_fixed_new ();
  gtk_widget_show (fixed21);
  gtk_container_add (GTK_CONTAINER (ajout_bureau_), fixed21);

  label107 = gtk_label_new (_("<b>Ajouter un bureau de vote</b>"));
  gtk_widget_show (label107);
  gtk_fixed_put (GTK_FIXED (fixed21), label107, 8, 32);
  gtk_widget_set_size_request (label107, 488, 56);
  gtk_label_set_use_markup (GTK_LABEL (label107), TRUE);

  table9 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table9);
  gtk_fixed_put (GTK_FIXED (fixed21), table9, 40, 176);
  gtk_widget_set_size_request (table9, 432, 232);
  gtk_table_set_row_spacings (GTK_TABLE (table9), 15);
  gtk_table_set_col_spacings (GTK_TABLE (table9), 35);

  label108 = gtk_label_new (_("ID agent de bureau"));
  gtk_widget_show (label108);
  gtk_table_attach (GTK_TABLE (table9), label108, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label108), 0, 0.5);

  label109 = gtk_label_new (_("Capacit\303\251 electeurs"));
  gtk_widget_show (label109);
  gtk_table_attach (GTK_TABLE (table9), label109, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label109), 0, 0.5);

  label110 = gtk_label_new (_("Capacit\303\251 observateurs"));
  gtk_widget_show (label110);
  gtk_table_attach (GTK_TABLE (table9), label110, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label110), 0, 0.5);

  label111 = gtk_label_new (_("Adress"));
  gtk_widget_show (label111);
  gtk_table_attach (GTK_TABLE (table9), label111, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label111), 0, 0.5);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_table_attach (GTK_TABLE (table9), scrolledwindow2, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  textview2 = gtk_text_view_new ();
  gtk_widget_show (textview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), textview2);
  gtk_widget_set_size_request (textview2, -1, 109);
  gtk_text_view_set_pixels_above_lines (GTK_TEXT_VIEW (textview2), 9);
  gtk_text_view_set_pixels_inside_wrap (GTK_TEXT_VIEW (textview2), 10);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview2)), _("Adress here"), -1);

  entry23 = gtk_entry_new ();
  gtk_widget_show (entry23);
  gtk_table_attach (GTK_TABLE (table9), entry23, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry23), 8226);

  entry24 = gtk_entry_new ();
  gtk_widget_show (entry24);
  gtk_table_attach (GTK_TABLE (table9), entry24, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry24), 8226);

  entry25 = gtk_entry_new ();
  gtk_widget_show (entry25);
  gtk_table_attach (GTK_TABLE (table9), entry25, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (entry25), _("agent_id_here"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry25), 8226);

  button33 = gtk_button_new ();
  gtk_widget_show (button33);
  gtk_fixed_put (GTK_FIXED (fixed21), button33, 384, 472);
  gtk_widget_set_size_request (button33, 82, 32);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button33), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image32 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_box_pack_start (GTK_BOX (hbox15), image32, FALSE, FALSE, 0);

  label112 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label112);
  gtk_box_pack_start (GTK_BOX (hbox15), label112, FALSE, FALSE, 0);

  button34 = gtk_button_new ();
  gtk_widget_show (button34);
  gtk_fixed_put (GTK_FIXED (fixed21), button34, 288, 472);
  gtk_widget_set_size_request (button34, 80, 32);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button34), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image33 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image33);
  gtk_box_pack_start (GTK_BOX (hbox16), image33, FALSE, FALSE, 0);

  label113 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label113);
  gtk_box_pack_start (GTK_BOX (hbox16), label113, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_bureau_, ajout_bureau_, "ajout_bureau_");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, fixed21, "fixed21");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, label107, "label107");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, table9, "table9");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, label108, "label108");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, label109, "label109");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, label110, "label110");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, label111, "label111");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, textview2, "textview2");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, entry23, "entry23");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, entry24, "entry24");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, entry25, "entry25");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, button33, "button33");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, image32, "image32");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, label112, "label112");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, button34, "button34");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, image33, "image33");
  GLADE_HOOKUP_OBJECT (ajout_bureau_, label113, "label113");

  return ajout_bureau_;
}

GtkWidget*
create_Gestion_Bureau_de_vote (void)
{
  GtkWidget *Gestion_Bureau_de_vote;
  GtkWidget *fixed22;
  GtkWidget *label114;
  GtkWidget *label115;
  GtkWidget *button35;
  GtkWidget *image34;
  GtkWidget *image35;
  GtkWidget *treeview7;
  GtkWidget *button36;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image36;
  GtkWidget *label116;
  GtkWidget *button37;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image37;
  GtkWidget *label117;
  GtkWidget *button38;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image38;
  GtkWidget *label118;

  Gestion_Bureau_de_vote = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Gestion_Bureau_de_vote, 920, 510);
  gtk_window_set_title (GTK_WINDOW (Gestion_Bureau_de_vote), _("Gestion bureau de vote"));
  gtk_window_set_position (GTK_WINDOW (Gestion_Bureau_de_vote), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (Gestion_Bureau_de_vote), FALSE);

  fixed22 = gtk_fixed_new ();
  gtk_widget_show (fixed22);
  gtk_container_add (GTK_CONTAINER (Gestion_Bureau_de_vote), fixed22);

  label114 = gtk_label_new (_("Bonjour Mr"));
  gtk_widget_show (label114);
  gtk_fixed_put (GTK_FIXED (fixed22), label114, 792, 16);
  gtk_widget_set_size_request (label114, 96, 24);

  label115 = gtk_label_new (_("<b>Admin</b>"));
  gtk_widget_show (label115);
  gtk_fixed_put (GTK_FIXED (fixed22), label115, 800, 40);
  gtk_widget_set_size_request (label115, 72, 24);
  gtk_label_set_use_markup (GTK_LABEL (label115), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (label115), TRUE);

  button35 = gtk_button_new_with_mnemonic (_("Deconnecter"));
  gtk_widget_show (button35);
  gtk_fixed_put (GTK_FIXED (fixed22), button35, 800, 72);
  gtk_widget_set_size_request (button35, 96, 24);

  image34 = create_pixmap (Gestion_Bureau_de_vote, "bureau_de_vote.png");
  gtk_widget_show (image34);
  gtk_fixed_put (GTK_FIXED (fixed22), image34, 192, 16);
  gtk_widget_set_size_request (image34, 496, 80);

  image35 = create_pixmap (Gestion_Bureau_de_vote, NULL);
  gtk_widget_show (image35);
  gtk_fixed_put (GTK_FIXED (fixed22), image35, 40, 24);
  gtk_widget_set_size_request (image35, 72, 64);

  treeview7 = gtk_tree_view_new ();
  gtk_widget_show (treeview7);
  gtk_fixed_put (GTK_FIXED (fixed22), treeview7, 48, 120);
  gtk_widget_set_size_request (treeview7, 824, 216);

  button36 = gtk_button_new ();
  gtk_widget_show (button36);
  gtk_fixed_put (GTK_FIXED (fixed22), button36, 784, 368);
  gtk_widget_set_size_request (button36, 88, 32);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button36), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image36 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image36);
  gtk_box_pack_start (GTK_BOX (hbox17), image36, FALSE, FALSE, 0);

  label116 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label116);
  gtk_box_pack_start (GTK_BOX (hbox17), label116, FALSE, FALSE, 0);

  button37 = gtk_button_new ();
  gtk_widget_show (button37);
  gtk_fixed_put (GTK_FIXED (fixed22), button37, 664, 368);
  gtk_widget_set_size_request (button37, 96, 32);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button37), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image37 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image37);
  gtk_box_pack_start (GTK_BOX (hbox18), image37, FALSE, FALSE, 0);

  label117 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label117);
  gtk_box_pack_start (GTK_BOX (hbox18), label117, FALSE, FALSE, 0);

  button38 = gtk_button_new ();
  gtk_widget_show (button38);
  gtk_fixed_put (GTK_FIXED (fixed22), button38, 544, 368);
  gtk_widget_set_size_request (button38, 106, 32);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button38), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image38 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image38);
  gtk_box_pack_start (GTK_BOX (hbox19), image38, FALSE, FALSE, 0);

  label118 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label118);
  gtk_box_pack_start (GTK_BOX (hbox19), label118, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_Bureau_de_vote, Gestion_Bureau_de_vote, "Gestion_Bureau_de_vote");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, fixed22, "fixed22");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, label114, "label114");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, label115, "label115");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, button35, "button35");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, image34, "image34");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, image35, "image35");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, treeview7, "treeview7");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, button36, "button36");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, image36, "image36");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, label116, "label116");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, button37, "button37");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, image37, "image37");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, label117, "label117");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, button38, "button38");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, image38, "image38");
  GLADE_HOOKUP_OBJECT (Gestion_Bureau_de_vote, label118, "label118");

  return Gestion_Bureau_de_vote;
}

GtkWidget*
create_PanneauAgent (void)
{
  GtkWidget *PanneauAgent;
  GtkWidget *fixed23;
  GtkWidget *image39;
  GtkWidget *label119;
  GtkWidget *label120;
  GtkWidget *button39;
  GtkWidget *image40;
  GtkWidget *treeview8;
  GtkWidget *label121;
  GtkWidget *button40;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image41;
  GtkWidget *label122;
  GtkWidget *button41;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image42;
  GtkWidget *label123;
  GtkWidget *button42;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image43;
  GtkWidget *label124;

  PanneauAgent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (PanneauAgent, 920, 510);
  gtk_window_set_title (GTK_WINDOW (PanneauAgent), _("Panneau agent de bureau"));

  fixed23 = gtk_fixed_new ();
  gtk_widget_show (fixed23);
  gtk_container_add (GTK_CONTAINER (PanneauAgent), fixed23);

  image39 = create_pixmap (PanneauAgent, "panneauAgent.png");
  gtk_widget_show (image39);
  gtk_fixed_put (GTK_FIXED (fixed23), image39, 152, 24);
  gtk_widget_set_size_request (image39, 576, 56);

  label119 = gtk_label_new (_("Bonjour Mr"));
  gtk_widget_show (label119);
  gtk_fixed_put (GTK_FIXED (fixed23), label119, 800, 16);
  gtk_widget_set_size_request (label119, 96, 32);

  label120 = gtk_label_new (_("<b>Agent</b>"));
  gtk_widget_show (label120);
  gtk_fixed_put (GTK_FIXED (fixed23), label120, 808, 40);
  gtk_widget_set_size_request (label120, 80, 24);
  gtk_label_set_use_markup (GTK_LABEL (label120), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (label120), TRUE);

  button39 = gtk_button_new_with_mnemonic (_("Deconnecter"));
  gtk_widget_show (button39);
  gtk_fixed_put (GTK_FIXED (fixed23), button39, 808, 72);
  gtk_widget_set_size_request (button39, 96, 24);

  image40 = create_pixmap (PanneauAgent, NULL);
  gtk_widget_show (image40);
  gtk_fixed_put (GTK_FIXED (fixed23), image40, 24, 24);
  gtk_widget_set_size_request (image40, 64, 56);

  treeview8 = gtk_tree_view_new ();
  gtk_widget_show (treeview8);
  gtk_fixed_put (GTK_FIXED (fixed23), treeview8, 40, 176);
  gtk_widget_set_size_request (treeview8, 840, 216);

  label121 = gtk_label_new (_("<b>Liste des observateaurs</b>"));
  gtk_widget_show (label121);
  gtk_fixed_put (GTK_FIXED (fixed23), label121, 40, 136);
  gtk_widget_set_size_request (label121, 184, 24);
  gtk_label_set_use_markup (GTK_LABEL (label121), TRUE);

  button40 = gtk_button_new ();
  gtk_widget_show (button40);
  gtk_fixed_put (GTK_FIXED (fixed23), button40, 800, 432);
  gtk_widget_set_size_request (button40, 80, 32);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button40), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image41 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image41);
  gtk_box_pack_start (GTK_BOX (hbox20), image41, FALSE, FALSE, 0);

  label122 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label122);
  gtk_box_pack_start (GTK_BOX (hbox20), label122, FALSE, FALSE, 0);

  button41 = gtk_button_new ();
  gtk_widget_show (button41);
  gtk_fixed_put (GTK_FIXED (fixed23), button41, 696, 432);
  gtk_widget_set_size_request (button41, 88, 32);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button41), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image42 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image42);
  gtk_box_pack_start (GTK_BOX (hbox21), image42, FALSE, FALSE, 0);

  label123 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label123);
  gtk_box_pack_start (GTK_BOX (hbox21), label123, FALSE, FALSE, 0);

  button42 = gtk_button_new ();
  gtk_widget_show (button42);
  gtk_fixed_put (GTK_FIXED (fixed23), button42, 576, 432);
  gtk_widget_set_size_request (button42, 104, 32);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button42), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image43 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image43);
  gtk_box_pack_start (GTK_BOX (hbox22), image43, FALSE, FALSE, 0);

  label124 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label124);
  gtk_box_pack_start (GTK_BOX (hbox22), label124, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (PanneauAgent, PanneauAgent, "PanneauAgent");
  GLADE_HOOKUP_OBJECT (PanneauAgent, fixed23, "fixed23");
  GLADE_HOOKUP_OBJECT (PanneauAgent, image39, "image39");
  GLADE_HOOKUP_OBJECT (PanneauAgent, label119, "label119");
  GLADE_HOOKUP_OBJECT (PanneauAgent, label120, "label120");
  GLADE_HOOKUP_OBJECT (PanneauAgent, button39, "button39");
  GLADE_HOOKUP_OBJECT (PanneauAgent, image40, "image40");
  GLADE_HOOKUP_OBJECT (PanneauAgent, treeview8, "treeview8");
  GLADE_HOOKUP_OBJECT (PanneauAgent, label121, "label121");
  GLADE_HOOKUP_OBJECT (PanneauAgent, button40, "button40");
  GLADE_HOOKUP_OBJECT (PanneauAgent, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (PanneauAgent, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (PanneauAgent, image41, "image41");
  GLADE_HOOKUP_OBJECT (PanneauAgent, label122, "label122");
  GLADE_HOOKUP_OBJECT (PanneauAgent, button41, "button41");
  GLADE_HOOKUP_OBJECT (PanneauAgent, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (PanneauAgent, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (PanneauAgent, image42, "image42");
  GLADE_HOOKUP_OBJECT (PanneauAgent, label123, "label123");
  GLADE_HOOKUP_OBJECT (PanneauAgent, button42, "button42");
  GLADE_HOOKUP_OBJECT (PanneauAgent, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (PanneauAgent, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (PanneauAgent, image43, "image43");
  GLADE_HOOKUP_OBJECT (PanneauAgent, label124, "label124");

  return PanneauAgent;
}

GtkWidget*
create_Confirmation (void)
{
  GtkWidget *Confirmation;
  GtkWidget *fixed24;
  GtkWidget *label125;
  GtkWidget *checkbutton1;
  GtkWidget *button45;
  GtkWidget *button46;

  Confirmation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Confirmation, 0, 200);
  gtk_window_set_title (GTK_WINDOW (Confirmation), _("Confirmation"));
  gtk_window_set_position (GTK_WINDOW (Confirmation), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (Confirmation), FALSE);

  fixed24 = gtk_fixed_new ();
  gtk_widget_show (fixed24);
  gtk_container_add (GTK_CONTAINER (Confirmation), fixed24);

  label125 = gtk_label_new (_("Etes vous sure vous vouler supprimer X"));
  gtk_widget_show (label125);
  gtk_fixed_put (GTK_FIXED (fixed24), label125, 16, 24);
  gtk_widget_set_size_request (label125, 360, 80);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("Confirmer mon choix"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed24), checkbutton1, 64, 88);
  gtk_widget_set_size_request (checkbutton1, 184, 24);

  button45 = gtk_button_new_with_mnemonic (_("oui"));
  gtk_fixed_put (GTK_FIXED (fixed24), button45, 96, 144);
  gtk_widget_set_size_request (button45, 74, 29);
  gtk_widget_set_sensitive (button45, FALSE);
  GTK_WIDGET_UNSET_FLAGS (button45, GTK_CAN_FOCUS);
  gtk_button_set_relief (GTK_BUTTON (button45), GTK_RELIEF_HALF);

  button46 = gtk_button_new_with_mnemonic (_("Non"));
  gtk_widget_show (button46);
  gtk_fixed_put (GTK_FIXED (fixed24), button46, 184, 144);
  gtk_widget_set_size_request (button46, 74, 29);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Confirmation, Confirmation, "Confirmation");
  GLADE_HOOKUP_OBJECT (Confirmation, fixed24, "fixed24");
  GLADE_HOOKUP_OBJECT (Confirmation, label125, "label125");
  GLADE_HOOKUP_OBJECT (Confirmation, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (Confirmation, button45, "button45");
  GLADE_HOOKUP_OBJECT (Confirmation, button46, "button46");

  return Confirmation;
}

GtkWidget*
create_Gestion_Utilisateurs (void)
{
  GtkWidget *Gestion_Utilisateurs;
  GtkWidget *fixed25;
  GtkWidget *image46;
  GtkWidget *label126;
  GtkWidget *label127;
  GtkWidget *button47;
  GtkWidget *image47;
  GtkWidget *treeview9;
  GtkWidget *label128;
  GtkWidget *button48;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image48;
  GtkWidget *label129;
  GtkWidget *button49;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image49;
  GtkWidget *label130;

  Gestion_Utilisateurs = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Gestion_Utilisateurs, 920, 510);
  gtk_window_set_title (GTK_WINDOW (Gestion_Utilisateurs), _("Gestion des utilisateurs"));

  fixed25 = gtk_fixed_new ();
  gtk_widget_show (fixed25);
  gtk_container_add (GTK_CONTAINER (Gestion_Utilisateurs), fixed25);

  image46 = create_pixmap (Gestion_Utilisateurs, "gestionUtilisateurs.png");
  gtk_widget_show (image46);
  gtk_fixed_put (GTK_FIXED (fixed25), image46, 160, 24);
  gtk_widget_set_size_request (image46, 584, 64);

  label126 = gtk_label_new (_("Bonjour Mr"));
  gtk_widget_show (label126);
  gtk_fixed_put (GTK_FIXED (fixed25), label126, 808, 16);
  gtk_widget_set_size_request (label126, 88, 24);

  label127 = gtk_label_new (_("<b>Admin</b>"));
  gtk_widget_show (label127);
  gtk_fixed_put (GTK_FIXED (fixed25), label127, 816, 40);
  gtk_widget_set_size_request (label127, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label127), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (label127), TRUE);

  button47 = gtk_button_new_with_mnemonic (_("Deconnecter"));
  gtk_widget_show (button47);
  gtk_fixed_put (GTK_FIXED (fixed25), button47, 808, 64);
  gtk_widget_set_size_request (button47, 96, 24);

  image47 = create_pixmap (Gestion_Utilisateurs, NULL);
  gtk_widget_show (image47);
  gtk_fixed_put (GTK_FIXED (fixed25), image47, 40, 32);
  gtk_widget_set_size_request (image47, 72, 64);

  treeview9 = gtk_tree_view_new ();
  gtk_widget_show (treeview9);
  gtk_fixed_put (GTK_FIXED (fixed25), treeview9, 48, 152);
  gtk_widget_set_size_request (treeview9, 832, 224);

  label128 = gtk_label_new (_("<b>Liste des utilisateurs</b>"));
  gtk_widget_show (label128);
  gtk_fixed_put (GTK_FIXED (fixed25), label128, 40, 120);
  gtk_widget_set_size_request (label128, 168, 16);
  gtk_label_set_use_markup (GTK_LABEL (label128), TRUE);

  button48 = gtk_button_new ();
  gtk_widget_show (button48);
  gtk_fixed_put (GTK_FIXED (fixed25), button48, 792, 408);
  gtk_widget_set_size_request (button48, 88, 32);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button48), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image48 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image48);
  gtk_box_pack_start (GTK_BOX (hbox23), image48, FALSE, FALSE, 0);

  label129 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label129);
  gtk_box_pack_start (GTK_BOX (hbox23), label129, FALSE, FALSE, 0);

  button49 = gtk_button_new ();
  gtk_widget_show (button49);
  gtk_fixed_put (GTK_FIXED (fixed25), button49, 672, 408);
  gtk_widget_set_size_request (button49, 104, 32);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (button49), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image49 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image49);
  gtk_box_pack_start (GTK_BOX (hbox24), image49, FALSE, FALSE, 0);

  label130 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label130);
  gtk_box_pack_start (GTK_BOX (hbox24), label130, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_Utilisateurs, Gestion_Utilisateurs, "Gestion_Utilisateurs");
  GLADE_HOOKUP_OBJECT (Gestion_Utilisateurs, fixed25, "fixed25");
  GLADE_HOOKUP_OBJECT (Gestion_Utilisateurs, image46, "image46");
  GLADE_HOOKUP_OBJECT (Gestion_Utilisateurs, label126, "label126");
  GLADE_HOOKUP_OBJECT (Gestion_Utilisateurs, label127, "label127");
  GLADE_HOOKUP_OBJECT (Gestion_Utilisateurs, button47, "button47");
  GLADE_HOOKUP_OBJECT (Gestion_Utilisateurs, image47, "image47");
  GLADE_HOOKUP_OBJECT (Gestion_Utilisateurs, treeview9, "treeview9");
  GLADE_HOOKUP_OBJECT (Gestion_Utilisateurs, label128, "label128");
  GLADE_HOOKUP_OBJECT (Gestion_Utilisateurs, button48, "button48");
  GLADE_HOOKUP_OBJECT (Gestion_Utilisateurs, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (Gestion_Utilisateurs, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (Gestion_Utilisateurs, image48, "image48");
  GLADE_HOOKUP_OBJECT (Gestion_Utilisateurs, label129, "label129");
  GLADE_HOOKUP_OBJECT (Gestion_Utilisateurs, button49, "button49");
  GLADE_HOOKUP_OBJECT (Gestion_Utilisateurs, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (Gestion_Utilisateurs, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (Gestion_Utilisateurs, image49, "image49");
  GLADE_HOOKUP_OBJECT (Gestion_Utilisateurs, label130, "label130");

  return Gestion_Utilisateurs;
}

