/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *login_window;
  GtkWidget *panneau_admin_window;
  GtkWidget *Ajout___lection;
  GtkWidget *Gestion_elections;
  GtkWidget *electorPannel;
  GtkWidget *ajout_liste_electoral;
  GtkWidget *Reclamation;
  GtkWidget *Ajout_observateur;
  GtkWidget *ajout_bureau_;
  GtkWidget *Gestion_Bureau_de_vote;
  GtkWidget *PanneauAgent;
  GtkWidget *Confirmation;
  GtkWidget *Gestion_Utilisateurs;
  GtkWidget *admin_window;
  GtkWidget *ajouter_electeur_window;
  GtkWidget *ajouter_observateur_window;
  GtkWidget *edit_electeur_window;
  GtkWidget *edit_observateur_window;
  GtkWidget *agent_window;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  login_window = create_login_window ();
  gtk_widget_show (login_window);
  /*panneau_admin_window = create_panneau_admin_window ();
  gtk_widget_show (panneau_admin_window);
  Ajout___lection = create_Ajout___lection ();
  gtk_widget_show (Ajout___lection);
  Gestion_elections = create_Gestion_elections ();
  gtk_widget_show (Gestion_elections);
  electorPannel = create_electorPannel ();
  gtk_widget_show (electorPannel);
  ajout_liste_electoral = create_ajout_liste_electoral ();
  gtk_widget_show (ajout_liste_electoral);
  Reclamation = create_Reclamation ();
  gtk_widget_show (Reclamation);
  Ajout_observateur = create_Ajout_observateur ();
  gtk_widget_show (Ajout_observateur);
  ajout_bureau_ = create_ajout_bureau_ ();
  gtk_widget_show (ajout_bureau_);
  Gestion_Bureau_de_vote = create_Gestion_Bureau_de_vote ();
  gtk_widget_show (Gestion_Bureau_de_vote);
  PanneauAgent = create_PanneauAgent ();
  gtk_widget_show (PanneauAgent);
  Confirmation = create_Confirmation ();
  gtk_widget_show (Confirmation);
  Gestion_Utilisateurs = create_Gestion_Utilisateurs ();
  gtk_widget_show (Gestion_Utilisateurs);
  admin_window = create_admin_window ();
  gtk_widget_show (admin_window);
  ajouter_electeur_window = create_ajouter_electeur_window ();
  gtk_widget_show (ajouter_electeur_window);
  ajouter_observateur_window = create_ajouter_observateur_window ();
  gtk_widget_show (ajouter_observateur_window);
  edit_electeur_window = create_edit_electeur_window ();
  gtk_widget_show (edit_electeur_window);
  edit_observateur_window = create_edit_observateur_window ();
  gtk_widget_show (edit_observateur_window);
  agent_window = create_agent_window ();
  gtk_widget_show (agent_window);*/

  gtk_main ();
  return 0;
}

